version: '3'
services:
  express:      
    container_name: express
    image: express
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./myapp:/app
    privileged: true
    tty: true


